name: Java CI with Maven

on:
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4
    
    - name: Set up JDK 11
      uses: actions/setup-java@v4
      with:
        java-version: '11'
        distribution: 'corretto'
        cache: maven
        
    - name: Install Specific Version of Maven
      run: |
        MAVEN_VERSION=3.9.8
        wget https://downloads.apache.org/maven/maven-3/$MAVEN_VERSION/binaries/apache-maven-$MAVEN_VERSION-bin.tar.gz
        tar -xzf apache-maven-$MAVEN_VERSION-bin.tar.gz
        sudo mv apache-maven-$MAVEN_VERSION /opt/maven
        echo "M2_HOME=/opt/maven" | sudo tee -a /etc/environment
        echo "PATH=\$PATH:\$M2_HOME/bin" | sudo tee -a /etc/environment
        source /etc/environment
        
    - name: Build with Maven
      run: mvn -B package --file pom.xml
      
    - name: Check Dependency Updates
      run: mvn versions:display-dependency-updates
   
    - name: Build with Maven
      run: mvn clean install
   
    - name: Run Tests
      run: mvn -X test
      
    - name: Run Checkstyle
      run: mvn checkstyle:check


    # - name: Generate Cucumber Reports
    #   run: mvn cucumber:report
      
    # - name: Publish Test Report
    #   uses: actions/upload-artifact@v3
    #   with:
    #     name: test-report
    #     path: target/cucumber-reports
